dataset: miniImageNet_spec
dataset_args: {
    root_path: /home/zit/21class/ZhengWang/Datasets/MiniImagenet,
    split: test,
    image_size: 84,
    patch_size: 21,
    patch_num: 36,
    local_augment: local_Crop}

shot: 1
#load: ./save/MODEL_FOLDER/EPOCH_X.pth
load: save/meta_miniImageNet_spec-1shot_meta-baseline-resnet12_6/max-va.pth
